//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// On Fri Jun  9 12:18:17 CEST 2023
//
//
// Ports:
// Name                         I/O  size props
// doit                           O     4
// CLK                            I     1 unused
// RST_N                          I     1 unused
// doit_pix                       I     4
//
// Combinational paths from inputs to outputs:
//   doit_pix -> doit
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module tt_um_negative(CLK,
		      RST_N,

		      doit_pix,
		      doit);
  input  CLK;
  input  RST_N;

  // value method doit
  input  [3 : 0] doit_pix;
  output [3 : 0] doit;

  // signals for module outputs
  wire [3 : 0] doit;

  // value method doit
  assign doit = 4'hF - doit_pix ;
endmodule  // tt_um_negative

